{% set version = "0.8.4" %}

package:
  name: pyoos
  version: {{ version }}

source:
  fn : pyoos-{{ version }}.tar.gz
  url: https://github.com/ioos/pyoos/archive/v{{ version }}.tar.gz
  sha256: 75a33c1d0f36e97a9a4da6eba8aedb48636f0753f5c361167155b3afad80c3d6

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - paegan
    - owslib
    - numpy
    - requests
    - fiona
    - beautifulsoup4
    - lxml

test:
  imports:
    - pyoos
    - pyoos.parsers
    - pyoos.collectors.nerrs
    - pyoos.collectors
    - pyoos.collectors.hads
    - pyoos.collectors.coops
    - pyoos.collectors.ndbc
    - pyoos.parsers.ioos
    - pyoos.collectors.usgs
    - pyoos.collectors.ioos
    - pyoos.parsers.ioos.one
    - pyoos.parsers.wqx
    - pyoos.utils
    - pyoos.collectors.awc
    - pyoos.collectors.wqp
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/ioos/pyoos
  license: GPL-3.0
  license_file: LICENSE
  summary: 'A Python library for collecting Met/Ocean observations.'

extra:
  recipe-maintainers:
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
