travis:
  secure:
    BINSTAR_TOKEN: eLgdRWk2jLfZjfr0WFI3hJf2iUb/Gws0KpdwPKnX4tgUiAWNcbvljT0tBBXtsTrKbT/JDkFLJvDwfeiDbs3kZsQRFdsUmOtyi2OtVs8EZeRGzl7ywWXQRC4saBK6BdQizXVJpvFoHBKLWW7AcgXUCC40f0Lcm6Zbhtbudek+tyzOP/4xUiCg/EeiFXyc7zjjapgir04p0p9/EOTaonAkAZrnhw4Mv81uEo9EP+C5AAT/Rc/0dcAfH8w/1Zjfv4jb1jgYhyxcScPwtg7AbTDSg4w24kVEp2s7GG70KHJDSAR/VDBdIfylQoiRE1egx4lfJ6N4YiBO5FVgQdTxAe4u+xbumGFdy+JR+ds8TddOmc9rfdOPRgz7j8zF9Y97LzZh1YHP6t37Bi1MQwS2IBYAjqAXGtWGDULpFVR5pkSOrfx8wLEmvRy5rtv+uiWq4yOWCxyUNaTXNoaN0r4bKiPWVu5tiUbxEZqh4+l+stVpceGs0slLjoPMKyON4K6LjgfS86oLAfMUg77EdDR7LjvVyYeykR/l8w0TeMjhZt0Ph1BlUvJGiB0Q5+XgilqlwI2e4yg+2G/8VeX0N3ISvl8gu4esFhxjV36kkIPxLWn6CdqXBohkiMjJfkxKtweSOFKGykdqsyeDrkfkIf892kJKeU/mDIfCxQUlIC8P7yDZV+E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
