travis:
  secure:
    BINSTAR_TOKEN: hoWWaFGcRBQXJSVAYYz8OUReHLU1FyBlTe/HUKq6GuC4aFCJWwsoTiOSs9pWxWk45M2p28ff6UOr7/n3/g3VIEFO06D1R1cPyQmLgKyYbPOh123+NfDUYa1iPH4NirY11YXAcey3Qs2Ko4iDcoKwg9zjf7NJuhlX1QLMidZlRvwX+Zdp7/n/RJFAdZ7OwkLEpa14jYhyCXw/NCZQPCgCSwR2EP9RLsRxjCjZYOAJkYErYzk/hIzjLKPGUZFend0FhjyMpk1QFsYOFsv0dVl4AjDTBY5hgcRdPdz2k3SWo6AVlUlsMco5+990NA+5Ns77ndIMUv/gX2gHntGg21yHML5nA/kB85ZWqQDyrZQLAuHGVMPooA0TeYXf/m08zW9weVieoFy+GkDiqt7oWq0uPqiuHBEIQpmatJxJ+y2og0EAdjRffaYiULHTEkfSzvcvMywZ9LVJyqi59xi5OOcF93ByaJxrEIPFp1xznOJRXxPlnJ4UzElCBUlS3XUSAVKQAE06+8wQ/KBKNrhgZaCHvUT/GjtjORe2mk2bk6jyAwDEL+x6v3lfH2OCfqoGkTdLs3Cvdw+V7fe/6q2XbDxL23KPXhQ7tJ3I34v/RjP2D8fBK6KW0HCHQzXNtYeMOREIidszxAs8Bh5n8fGB/QB0A5SePx/SqrGkwJHmYzOwIXE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
